/* Auto-generated by genmsg_cpp for file /home/ics/ros_workspace/mobile_base/omni_base_msgs/msg/PowerState.msg */
#ifndef OMNI_BASE_MSGS_MESSAGE_POWERSTATE_H
#define OMNI_BASE_MSGS_MESSAGE_POWERSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace omni_base_msgs
{
template <class ContainerAllocator>
struct PowerState_ {
  typedef PowerState_<ContainerAllocator> Type;

  PowerState_()
  : name()
  , enabled(false)
  {
  }

  PowerState_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , enabled(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef uint8_t _enabled_type;
  uint8_t enabled;


  typedef boost::shared_ptr< ::omni_base_msgs::PowerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_base_msgs::PowerState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PowerState
typedef  ::omni_base_msgs::PowerState_<std::allocator<void> > PowerState;

typedef boost::shared_ptr< ::omni_base_msgs::PowerState> PowerStatePtr;
typedef boost::shared_ptr< ::omni_base_msgs::PowerState const> PowerStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::omni_base_msgs::PowerState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::omni_base_msgs::PowerState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace omni_base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::omni_base_msgs::PowerState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::omni_base_msgs::PowerState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::omni_base_msgs::PowerState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0a25a4ba6b569752be722a73fae9c6c7";
  }

  static const char* value(const  ::omni_base_msgs::PowerState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0a25a4ba6b569752ULL;
  static const uint64_t static_value2 = 0xbe722a73fae9c6c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_base_msgs::PowerState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "omni_base_msgs/PowerState";
  }

  static const char* value(const  ::omni_base_msgs::PowerState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::omni_base_msgs::PowerState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name  # name of the relay / actuator \n\
bool enabled # whether the relay is closed / the actuator has power\n\
\n\
";
  }

  static const char* value(const  ::omni_base_msgs::PowerState_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::omni_base_msgs::PowerState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.enabled);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PowerState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_base_msgs::PowerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::omni_base_msgs::PowerState_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OMNI_BASE_MSGS_MESSAGE_POWERSTATE_H

